services:
  # migrations:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   # ports:
  #   #   - "8081:8081"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DOCKER: 1
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   restart: on-failure

  db:
    image: postgres:17
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  database: